// frontend/src/routes/auth/login/+page.svelte
<script lang="ts">
  async function loginWithGoogle() {
    try {
      const res = await fetch("/api/v1/auth/google");
      const { data } = await res.json();
      window.location.href = data.url; // Navigate to Google OAuth login
    } catch (err) {
      // TODO: gestisci (?)
      console.log("Errore")
      // status = "error";
    }
  }
</script>

<svelte:head>
  <title>Accedi | Shokora</title>
</svelte:head>

<div class="min-w-full min-h-screen flex flex-col justify-center items-center">
  <h1>Accedi</h1>
  <button onclick={loginWithGoogle}>Accedi con google</button>
</div>

// frontend/app/auth/login/page.tsx
"use client"

import { Button } from "@/components/ui/button";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter();

  const handleGoogleLogin = async () => {
    try {
      const res = await fetch("/api/v1/auth/google");

      if (!res.ok) {
        // TODO: gestisci (throw error e gestione nel catch?)
        console.log("Errore login google");
      }

      const data = await res.json();

      router.push(data.data.url);

    } catch (err) {
      // TODO: gestisci
      console.log(err);
    }
  }

  return (
    <div className="flex flex-col gap-8 justify-center align-center">
      <h1>Login Page</h1>
      <Button onClick={handleGoogleLogin}>Accedi con Google</Button>
    </div>
  );
}
