// frontend/app/auth/google/callback/page.tsx
"use client"

// TODO: cambia (metti tipo caricamento o altro)

import { useRouter, useSearchParams } from "next/navigation";
import { useEffect } from "react";

export default function GoogleCallbackPage() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const state = searchParams.get("state");
  const code = searchParams.get("code");


  useEffect(() => {
    if (!state || !code) {
      router.replace("/auth/login?error=oauth_failed"); // TODO: fai pagina per errori auth (?)
      return;
    }

    try {
      fetch("/api/v1/auth/google/callback", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include", // TODO: usalo (oppure "same-origin" ma potrebbe dare problemi, almeno in dev) in tutte le richieste non pubbliche non legate all'auth
        body: JSON.stringify({ state, code }),
      }).catch(_ => {
        router.replace("/auth/login?error=oauth_failed");
      });

    } catch (err) {
      router.replace("/auth/login?error=oauth_failed");
    }

  }, []);

  return (
    <div>
      <h1>Google Callback Page</h1>
    </div>
  );
}

// frontend-old/src/routes/auth/google/callback/+page.svelte
<script>
    import { onMount } from 'svelte'
    import { goto } from '$app/navigation'

    onMount(async () => {
      try {
        // Get params from url
        const params = new URLSearchParams(window.location.search)
        const code = params.get('code')
        const state = params.get('state')

        if (!code || !state) {
            goto('/login?error=oauth_failed') // TODO: aggiungi errore in quella pagina (da param)
            return
        }

        // Fetch google callback
        const res = await fetch('/api/v1/auth/google/callback', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            credentials: 'include',
            body: JSON.stringify({ code, state })
        })

        // Check res and navigate
        if (res.ok) {
            goto('/')
        } else {
            goto('/login?error=oauth_failed')
        }
      } catch {
        goto('/login?error=oauth_failed')
      }
    })
</script>

<p>Accesso in corso...</p>
